# Generated by Django 3.2.6 on 2022-05-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BornesHorsRue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nNoBorne', models.IntegerField()),
                ('sTerrain', models.CharField(max_length=20)),
                ('sNomRuePrincipale', models.CharField(max_length=200)),
                ('sStatut', models.CharField(max_length=2)),
                ('nLongitude', models.FloatField()),
                ('nLatitude', models.FloatField()),
                ('Lun', models.BooleanField()),
                ('Mar', models.BooleanField()),
                ('Mer', models.BooleanField()),
                ('Jeu', models.BooleanField()),
                ('Ven', models.BooleanField()),
                ('Sam', models.BooleanField()),
                ('Dim', models.BooleanField()),
                ('dtHeureDebutAP', models.TimeField()),
                ('dtHeureFinAP', models.TimeField()),
                ('nTarifHoraire', models.IntegerField()),
                ('nMax', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BornesSurRue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DateExportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EmplacementReglementation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Periodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReglementationPeriode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Reglementations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
