# Generated by Django 3.2.6 on 2022-05-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BornesHorsRue',
            new_name='BornesHorsRueDB',
        ),
    ]
