# Generated by Django 3.2.6 on 2022-05-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20220506_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placesdb',
            name='sNoPlace',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
