# Generated by Django 3.2.6 on 2022-05-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_placesdb_ntarifmax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placesdb',
            name='sAutreTete',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
